# Generated by Django 3.2 on 2021-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_resume_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(max_length=250, verbose_name='Образование'),
        ),
    ]
